name: ci
on: [push]
jobs:
  tests-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm ci
      - name: Cypress Tests
        run: npx cypress run --component
